# Generated by Django 3.2.6 on 2022-09-01 07:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('^[a-z0-9]+[\\._]?[a-z0-9]+[@]\\w+[.]\\w{2,3}$', code='Invalid Email', message='Invalid Email')])),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{10,15}$')])),
                ('designation', models.CharField(choices=[('Student', 'Student'), ('Developer', 'Developer'), ('Businessman', 'Businessman')], max_length=200)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
