# Generated by Django 3.2.6 on 2022-09-07 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appclient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(blank=True, null=True)),
                ('chatbot_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='chatbot-img/')),
                ('url_link', models.CharField(blank=True, max_length=200, null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appclient.clientregistration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
